version: '2'
services:
  db:
    build: ./db
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - 3308:3306
    volumes:
      - sql-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

  app: &app_base
    build: 
      context: ./rails_app
      args:
        PORT: 3000
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: ./rails_app/.env
    volumes:
      - ./rails_app:/app      
    ports:
      - 3000:3000
    links:
      - db
    tty: true 
    stdin_open: true

  spring: 
    <<: *app_base
    command: ["bundle", "exec", "spring", "server"]
    ports: []
    tty: false
    stdin_open: false  
    pid: host
    environment:
      SPRING_SOCKET: /tmp/spring/spring.sock
    volumes:
      - ./rails_app:/app  
      - spring:/tmp/spring/

volumes:
  sql-data:
  spring:
